name: nexus-vault-indexer
contracts:
  - name: Vault
    handler: src/EventHandlers.ts
    events:
      - event: Deposit(bytes32 indexed requestHash, address from)
      - event: Fulfilment(bytes32 indexed requestHash, address from, address solver)
networks:
  - id: 11155111      # Sepolia
    start_block: 10604152
    contracts:
      - name: Vault
        address:
          - "0x86B60E813f9b739516dDbDc443526be5Ef8336aa"
  - id: 11155420      # OP Sepolia
    start_block: 41673742
    contracts:
      - name: Vault
        address:
          - "0x86B60E813f9b739516dDbDc443526be5Ef8336aa"
  - id: 421614      # Arbitrum Sepolia
    start_block: 257100000
    contracts:
      - name: Vault
        address:
          - "0x86B60E813f9b739516dDbDc443526be5Ef8336aa"
  - id: 84532      # Base Sepolia
    start_block: 39860000
    contracts:
      - name: Vault
        address:
          - "0x86B60E813f9b739516dDbDc443526be5Ef8336aa"
  - id: 80002      # Polygon Amoy
    start_block: 36186485
    contracts:
      - name: Vault
        address:
          - "0x86B60E813f9b739516dDbDc443526be5Ef8336aa"
unordered_multichain_mode: true
field_selection:
  transaction_fields:
    - hash
